chore(NODE-6319): upgrade dependencies
mongodb-js/dbx-js-tools pull request #14
Opened 2024-08-08 02:25 UTC by baileympearson

### Description

#### What is changing?

##### Is there new documentation needed for these changes?

#### What is the motivation for this change?

### Double check the following

- [ ] Ran `npm run check:eslint` script
- [ ] Self-review completed using the [steps outlined here](https://github.com/mongodb/node-mongodb-native/blob/HEAD/CONTRIBUTING.md#reviewer-guidelines)
- [ ] PR title follows the [correct format](https://www.conventionalcommits.org/en/v1.0.0/): `type(NODE-xxxx)[!]: description`
  - Example: `feat(NODE-1234)!: rewriting everything in coffeescript`
- [ ] Changes are covered by tests
- [ ] New TODOs have a related JIRA ticket

2024-08-09 18:11 UTC, aditi-khare-mongoDB requested changes

2024-08-09 18:11 UTC, aditi-khare-mongoDB commented on .eslintrc.json
>      "simple-import-sort/exports": "error",
We want to add in the `eslint/no-duplicate-imports`, right? (linked [here](https://eslint.org/docs/latest/rules/no-duplicate-imports))

2024-08-15 15:13 UTC, aditi-khare-mongoDB approved these changes
Waiting for our conversation on virtual office to resolve before merging - so we can add in other rules if needed

2024-08-15 15:38 UTC, aditi-khare-mongoDB requested changes

2024-08-15 15:38 UTC, aditi-khare-mongoDB commented on package.json
>    "devDependencies": {
Some tests are failing, any idea why?

2024-08-15 15:47 UTC, baileympearson commented on package.json
>    "devDependencies": {
The tests are also failing on `main`.

2024-08-16 15:41 UTC, aditi-khare-mongoDB approved these changes

2024-08-16 15:41 UTC, merged